const CACTUS_VERSION = '0.4.2stable';

const OPEN_FILE  = 1;  //IPC commands
      ENQUEU_FILE  = 2;
      OPEN_AS_NEXT = 3;
      VOLUME_UP  = 4;
      VOLUME_DOWN = 5;
      NEXT_TRACK = 6;
      PREV_TRACK = 7;
      STOP_PLAYING = 8;
      START_PLAYING = 9;	
      PAUSE_PLAYING = 10;	
      
const AUPLOAD = 3;  //file action/state IDs
      ANOTHING = -1;
      AREMOVE = 2;
      AONPLAYER = 1;
      
const URLID = 'url://';
