{
/****************************************************************************

rxcconst.res

Delphi VCL Extensions (RX)
Copyright (c) 1995 AO ROSNO
Copyright (c) 1997 Master-Bank

*****************************************************************************/
}
  sBrowse          = 'Browse';
  sDefaultFilter   = 'All files (*.*)|*.*';
  sDateDlgTitle    = 'Select a Date';
  sNextYear        = 'Next Year|';
  sNextMonth       = 'Next Month|';
  sPrevYear        = 'Previous Year|';
  sPrevMonth       = 'Previous Month|';
  sNotImplemented  = 'Function not yet implemented';
  sFileNotExec     = 'File specified is not an executable file, dynamic-link library, or icon file';
  sLoadLibError    = 'Could not load ''%s'' library';
  sDetails         = 'Details';
  sWindowsIcoFiles = 'Windows Ico files (*.ico)|*.ico|All files (*.*)|*.*';
  sToCurDate       = 'Set current date';

  
  
