const
  LGPL_Text =
'		  GNU LESSER GENERAL PUBLIC LICENSE' + LineEnding +
'		       Version 2.1, February 1999' + LineEnding +
'' + LineEnding +
' Copyright (C) 1991, 1999 Free Software Foundation, Inc.' + LineEnding +
'     59 Temple Place, Suite 330, Boston, MA  02111-1307  USA' + LineEnding +
' Everyone is permitted to copy and distribute verbatim copies' + LineEnding +
' of this license document, but changing it is not allowed.' + LineEnding +
'' + LineEnding +
'[This is the first released version of the Lesser GPL.  It also counts' + LineEnding +
' as the successor of the GNU Library Public License, version 2, hence' + LineEnding +
' the version number 2.1.]' + LineEnding +
'' + LineEnding +
'			    Preamble' + LineEnding +
'' + LineEnding +
'  The licenses for most software are designed to take away your' + LineEnding +
'freedom to share and change it.  By contrast, the GNU General Public' + LineEnding +
'Licenses are intended to guarantee your freedom to share and change' + LineEnding +
'free software--to make sure the software is free for all its users.' + LineEnding +
'' + LineEnding +
'  This license, the Lesser General Public License, applies to some' + LineEnding +
'specially designated software packages--typically libraries--of the' + LineEnding +
'Free Software Foundation and other authors who decide to use it.  You' + LineEnding +
'can use it too, but we suggest you first think carefully about whether' + LineEnding +
'this license or the ordinary General Public License is the better' + LineEnding +
'strategy to use in any particular case, based on the explanations below.' + LineEnding +
'' + LineEnding +
'  When we speak of free software, we are referring to freedom of use,' + LineEnding +
'not price.  Our General Public Licenses are designed to make sure that' + LineEnding +
'you have the freedom to distribute copies of free software (and charge' + LineEnding +
'for this service if you wish); that you receive source code or can get' + LineEnding +
'it if you want it; that you can change the software and use pieces of' + LineEnding +
'it in new free programs; and that you are informed that you can do' + LineEnding +
'these things.' + LineEnding +
'' + LineEnding +
'  To protect your rights, we need to make restrictions that forbid' + LineEnding +
'distributors to deny you these rights or to ask you to surrender these' + LineEnding +
'rights.  These restrictions translate to certain responsibilities for' + LineEnding +
'you if you distribute copies of the library or if you modify it.' + LineEnding +
'' + LineEnding +
'  For example, if you distribute copies of the library, whether gratis' + LineEnding +
'or for a fee, you must give the recipients all the rights that we gave' + LineEnding +
'you.  You must make sure that they, too, receive or can get the source' + LineEnding +
'code.  If you link other code with the library, you must provide' + LineEnding +
'complete object files to the recipients, so that they can relink them' + LineEnding +
'with the library after making changes to the library and recompiling' + LineEnding +
'it.  And you must show them these terms so they know their rights.' + LineEnding +
'' + LineEnding +
'  We protect your rights with a two-step method: (1) we copyright the' + LineEnding +
'library, and (2) we offer you this license, which gives you legal' + LineEnding +
'permission to copy, distribute and/or modify the library.' + LineEnding +
'' + LineEnding +
'  To protect each distributor, we want to make it very clear that' + LineEnding +
'there is no warranty for the free library.  Also, if the library is' + LineEnding +
'modified by someone else and passed on, the recipients should know' + LineEnding +
'that what they have is not the original version, so that the original' + LineEnding +
'author''''s reputation will not be affected by problems that might be' + LineEnding +
'introduced by others.' + LineEnding +
'' + LineEnding +
'  Finally, software patents pose a constant threat to the existence of' + LineEnding +
'any free program.  We wish to make sure that a company cannot' + LineEnding +
'effectively restrict the users of a free program by obtaining a' + LineEnding +
'restrictive license from a patent holder.  Therefore, we insist that' + LineEnding +
'any patent license obtained for a version of the library must be' + LineEnding +
'consistent with the full freedom of use specified in this license.' + LineEnding +
'' + LineEnding +
'  Most GNU software, including some libraries, is covered by the' + LineEnding +
'ordinary GNU General Public License.  This license, the GNU Lesser' + LineEnding +
'General Public License, applies to certain designated libraries, and' + LineEnding +
'is quite different from the ordinary General Public License.  We use' + LineEnding +
'this license for certain libraries in order to permit linking those' + LineEnding +
'libraries into non-free programs.' + LineEnding +
'' + LineEnding +
'  When a program is linked with a library, whether statically or using' + LineEnding +
'a shared library, the combination of the two is legally speaking a' + LineEnding +
'combined work, a derivative of the original library.  The ordinary' + LineEnding +
'General Public License therefore permits such linking only if the' + LineEnding +
'entire combination fits its criteria of freedom.  The Lesser General' + LineEnding +
'Public License permits more lax criteria for linking other code with' + LineEnding +
'the library.' + LineEnding +
'' + LineEnding +
'  We call this license the "Lesser" General Public License because it' + LineEnding +
'does Less to protect the user''''s freedom than the ordinary General' + LineEnding +
'Public License.  It also provides other free software developers Less' + LineEnding +
'of an advantage over competing non-free programs.  These disadvantages' + LineEnding +
'are the reason we use the ordinary General Public License for many' + LineEnding +
'libraries.  However, the Lesser license provides advantages in certain' + LineEnding +
'special circumstances.' + LineEnding +
'' + LineEnding +
'  For example, on rare occasions, there may be a special need to' + LineEnding +
'encourage the widest possible use of a certain library, so that it becomes' + LineEnding +
'a de-facto standard.  To achieve this, non-free programs must be' + LineEnding +
'allowed to use the library.  A more frequent case is that a free' + LineEnding +
'library does the same job as widely used non-free libraries.  In this' + LineEnding +
'case, there is little to gain by limiting the free library to free' + LineEnding +
'software only, so we use the Lesser General Public License.' + LineEnding +
'' + LineEnding +
'  In other cases, permission to use a particular library in non-free' + LineEnding +
'programs enables a greater number of people to use a large body of' + LineEnding +
'free software.  For example, permission to use the GNU C Library in' + LineEnding +
'non-free programs enables many more people to use the whole GNU' + LineEnding +
'operating system, as well as its variant, the GNU/Linux operating' + LineEnding +
'system.' + LineEnding +
'' + LineEnding +
'  Although the Lesser General Public License is Less protective of the' + LineEnding +
'users'''' freedom, it does ensure that the user of a program that is' + LineEnding +
'linked with the Library has the freedom and the wherewithal to run' + LineEnding +
'that program using a modified version of the Library.' + LineEnding +
'' + LineEnding +
'  The precise terms and conditions for copying, distribution and' + LineEnding +
'modification follow.  Pay close attention to the difference between a' + LineEnding +
'"work based on the library" and a "work that uses the library".  The' + LineEnding +
'former contains code derived from the library, whereas the latter must' + LineEnding +
'be combined with the library in order to run.' + LineEnding +
'' + LineEnding +
'		  GNU LESSER GENERAL PUBLIC LICENSE' + LineEnding +
'   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION' + LineEnding +
'' + LineEnding +
'  0. This License Agreement applies to any software library or other' + LineEnding +
'program which contains a notice placed by the copyright holder or' + LineEnding +
'other authorized party saying it may be distributed under the terms of' + LineEnding +
'this Lesser General Public License (also called "this License").' + LineEnding +
'Each licensee is addressed as "you".' + LineEnding +
'' + LineEnding +
'  A "library" means a collection of software functions and/or data' + LineEnding +
'prepared so as to be conveniently linked with application programs' + LineEnding +
'(which use some of those functions and data) to form executables.' + LineEnding +
'' + LineEnding +
'  The "Library", below, refers to any such software library or work' + LineEnding +
'which has been distributed under these terms.  A "work based on the' + LineEnding +
'Library" means either the Library or any derivative work under' + LineEnding +
'copyright law: that is to say, a work containing the Library or a' + LineEnding +
'portion of it, either verbatim or with modifications and/or translated' + LineEnding +
'straightforwardly into another language.  (Hereinafter, translation is' + LineEnding +
'included without limitation in the term "modification".)' + LineEnding +
'' + LineEnding +
'  "Source code" for a work means the preferred form of the work for' + LineEnding +
'making modifications to it.  For a library, complete source code means' + LineEnding +
'all the source code for all modules it contains, plus any associated' + LineEnding +
'interface definition files, plus the scripts used to control compilation' + LineEnding +
'and installation of the library.' + LineEnding +
'' + LineEnding +
'  Activities other than copying, distribution and modification are not' + LineEnding +
'covered by this License; they are outside its scope.  The act of' + LineEnding +
'running a program using the Library is not restricted, and output from' + LineEnding +
'such a program is covered only if its contents constitute a work based' + LineEnding +
'on the Library (independent of the use of the Library in a tool for' + LineEnding +
'writing it).  Whether that is true depends on what the Library does' + LineEnding +
'and what the program that uses the Library does.' + LineEnding +
'  ' + LineEnding +
'  1. You may copy and distribute verbatim copies of the Library''''s' + LineEnding +
'complete source code as you receive it, in any medium, provided that' + LineEnding +
'you conspicuously and appropriately publish on each copy an' + LineEnding +
'appropriate copyright notice and disclaimer of warranty; keep intact' + LineEnding +
'all the notices that refer to this License and to the absence of any' + LineEnding +
'warranty; and distribute a copy of this License along with the' + LineEnding +
'Library.' + LineEnding +
'' + LineEnding +
'  You may charge a fee for the physical act of transferring a copy,' + LineEnding +
'and you may at your option offer warranty protection in exchange for a' + LineEnding +
'fee.' + LineEnding +
'' + LineEnding +
'  2. You may modify your copy or copies of the Library or any portion' + LineEnding +
'of it, thus forming a work based on the Library, and copy and' + LineEnding +
'distribute such modifications or work under the terms of Section 1' + LineEnding +
'above, provided that you also meet all of these conditions:' + LineEnding +
'' + LineEnding +
'    a) The modified work must itself be a software library.' + LineEnding +
'' + LineEnding +
'    b) You must cause the files modified to carry prominent notices' + LineEnding +
'    stating that you changed the files and the date of any change.' + LineEnding +
'' + LineEnding +
'    c) You must cause the whole of the work to be licensed at no' + LineEnding +
'    charge to all third parties under the terms of this License.' + LineEnding +
'' + LineEnding +
'    d) If a facility in the modified Library refers to a function or a' + LineEnding +
'    table of data to be supplied by an application program that uses' + LineEnding +
'    the facility, other than as an argument passed when the facility' + LineEnding +
'    is invoked, then you must make a good faith effort to ensure that,' + LineEnding +
'    in the event an application does not supply such function or' + LineEnding +
'    table, the facility still operates, and performs whatever part of' + LineEnding +
'    its purpose remains meaningful.' + LineEnding +
'' + LineEnding +
'    (For example, a function in a library to compute square roots has' + LineEnding +
'    a purpose that is entirely well-defined independent of the' + LineEnding +
'    application.  Therefore, Subsection 2d requires that any' + LineEnding +
'    application-supplied function or table used by this function must' + LineEnding +
'    be optional: if the application does not supply it, the square' + LineEnding +
'    root function must still compute square roots.)' + LineEnding +
'' + LineEnding +
'These requirements apply to the modified work as a whole.  If' + LineEnding +
'identifiable sections of that work are not derived from the Library,' + LineEnding +
'and can be reasonably considered independent and separate works in' + LineEnding +
'themselves, then this License, and its terms, do not apply to those' + LineEnding +
'sections when you distribute them as separate works.  But when you' + LineEnding +
'distribute the same sections as part of a whole which is a work based' + LineEnding +
'on the Library, the distribution of the whole must be on the terms of' + LineEnding +
'this License, whose permissions for other licensees extend to the' + LineEnding +
'entire whole, and thus to each and every part regardless of who wrote' + LineEnding +
'it.' + LineEnding +
'' + LineEnding +
'Thus, it is not the intent of this section to claim rights or contest' + LineEnding +
'your rights to work written entirely by you; rather, the intent is to' + LineEnding +
'exercise the right to control the distribution of derivative or' + LineEnding +
'collective works based on the Library.' + LineEnding +
'' + LineEnding +
'In addition, mere aggregation of another work not based on the Library' + LineEnding +
'with the Library (or with a work based on the Library) on a volume of' + LineEnding +
'a storage or distribution medium does not bring the other work under' + LineEnding +
'the scope of this License.' + LineEnding +
'' + LineEnding +
'  3. You may opt to apply the terms of the ordinary GNU General Public' + LineEnding +
'License instead of this License to a given copy of the Library.  To do' + LineEnding +
'this, you must alter all the notices that refer to this License, so' + LineEnding +
'that they refer to the ordinary GNU General Public License, version 2,' + LineEnding +
'instead of to this License.  (If a newer version than version 2 of the' + LineEnding +
'ordinary GNU General Public License has appeared, then you can specify' + LineEnding +
'that version instead if you wish.)  Do not make any other change in' + LineEnding +
'these notices.' + LineEnding +
'' + LineEnding +
'  Once this change is made in a given copy, it is irreversible for' + LineEnding +
'that copy, so the ordinary GNU General Public License applies to all' + LineEnding +
'subsequent copies and derivative works made from that copy.' + LineEnding +
'' + LineEnding +
'  This option is useful when you wish to copy part of the code of' + LineEnding +
'the Library into a program that is not a library.' + LineEnding +
'' + LineEnding +
'  4. You may copy and distribute the Library (or a portion or' + LineEnding +
'derivative of it, under Section 2) in object code or executable form' + LineEnding +
'under the terms of Sections 1 and 2 above provided that you accompany' + LineEnding +
'it with the complete corresponding machine-readable source code, which' + LineEnding +
'must be distributed under the terms of Sections 1 and 2 above on a' + LineEnding +
'medium customarily used for software interchange.' + LineEnding +
'' + LineEnding +
'  If distribution of object code is made by offering access to copy' + LineEnding +
'from a designated place, then offering equivalent access to copy the' + LineEnding +
'source code from the same place satisfies the requirement to' + LineEnding +
'distribute the source code, even though third parties are not' + LineEnding +
'compelled to copy the source along with the object code.' + LineEnding +
'' + LineEnding +
'  5. A program that contains no derivative of any portion of the' + LineEnding +
'Library, but is designed to work with the Library by being compiled or' + LineEnding +
'linked with it, is called a "work that uses the Library".  Such a' + LineEnding +
'work, in isolation, is not a derivative work of the Library, and' + LineEnding +
'therefore falls outside the scope of this License.' + LineEnding +
'' + LineEnding +
'  However, linking a "work that uses the Library" with the Library' + LineEnding +
'creates an executable that is a derivative of the Library (because it' + LineEnding +
'contains portions of the Library), rather than a "work that uses the' + LineEnding +
'library".  The executable is therefore covered by this License.' + LineEnding +
'Section 6 states terms for distribution of such executables.' + LineEnding +
'' + LineEnding +
'  When a "work that uses the Library" uses material from a header file' + LineEnding +
'that is part of the Library, the object code for the work may be a' + LineEnding +
'derivative work of the Library even though the source code is not.' + LineEnding +
'Whether this is true is especially significant if the work can be' + LineEnding +
'linked without the Library, or if the work is itself a library.  The' + LineEnding +
'threshold for this to be true is not precisely defined by law.' + LineEnding +
'' + LineEnding +
'  If such an object file uses only numerical parameters, data' + LineEnding +
'structure layouts and accessors, and small macros and small inline' + LineEnding +
'functions (ten lines or less in length), then the use of the object' + LineEnding +
'file is unrestricted, regardless of whether it is legally a derivative' + LineEnding +
'work.  (Executables containing this object code plus portions of the' + LineEnding +
'Library will still fall under Section 6.)' + LineEnding +
'' + LineEnding +
'  Otherwise, if the work is a derivative of the Library, you may' + LineEnding +
'distribute the object code for the work under the terms of Section 6.' + LineEnding +
'Any executables containing that work also fall under Section 6,' + LineEnding +
'whether or not they are linked directly with the Library itself.' + LineEnding +
'' + LineEnding +
'  6. As an exception to the Sections above, you may also combine or' + LineEnding +
'link a "work that uses the Library" with the Library to produce a' + LineEnding +
'work containing portions of the Library, and distribute that work' + LineEnding +
'under terms of your choice, provided that the terms permit' + LineEnding +
'modification of the work for the customer''''s own use and reverse' + LineEnding +
'engineering for debugging such modifications.' + LineEnding +
'' + LineEnding +
'  You must give prominent notice with each copy of the work that the' + LineEnding +
'Library is used in it and that the Library and its use are covered by' + LineEnding +
'this License.  You must supply a copy of this License.  If the work' + LineEnding +
'during execution displays copyright notices, you must include the' + LineEnding +
'copyright notice for the Library among them, as well as a reference' + LineEnding +
'directing the user to the copy of this License.  Also, you must do one' + LineEnding +
'of these things:' + LineEnding +
'' + LineEnding +
'    a) Accompany the work with the complete corresponding' + LineEnding +
'    machine-readable source code for the Library including whatever' + LineEnding +
'    changes were used in the work (which must be distributed under' + LineEnding +
'    Sections 1 and 2 above); and, if the work is an executable linked' + LineEnding +
'    with the Library, with the complete machine-readable "work that' + LineEnding +
'    uses the Library", as object code and/or source code, so that the' + LineEnding +
'    user can modify the Library and then relink to produce a modified' + LineEnding +
'    executable containing the modified Library.  (It is understood' + LineEnding +
'    that the user who changes the contents of definitions files in the' + LineEnding +
'    Library will not necessarily be able to recompile the application' + LineEnding +
'    to use the modified definitions.)' + LineEnding +
'' + LineEnding +
'    b) Use a suitable shared library mechanism for linking with the' + LineEnding +
'    Library.  A suitable mechanism is one that (1) uses at run time a' + LineEnding +
'    copy of the library already present on the user''''s computer system,' + LineEnding +
'    rather than copying library functions into the executable, and (2)' + LineEnding +
'    will operate properly with a modified version of the library, if' + LineEnding +
'    the user installs one, as long as the modified version is' + LineEnding +
'    interface-compatible with the version that the work was made with.' + LineEnding +
'' + LineEnding +
'    c) Accompany the work with a written offer, valid for at' + LineEnding +
'    least three years, to give the same user the materials' + LineEnding +
'    specified in Subsection 6a, above, for a charge no more' + LineEnding +
'    than the cost of performing this distribution.' + LineEnding +
'' + LineEnding +
'    d) If distribution of the work is made by offering access to copy' + LineEnding +
'    from a designated place, offer equivalent access to copy the above' + LineEnding +
'    specified materials from the same place.' + LineEnding +
'' + LineEnding +
'    e) Verify that the user has already received a copy of these' + LineEnding +
'    materials or that you have already sent this user a copy.' + LineEnding +
'' + LineEnding +
'  For an executable, the required form of the "work that uses the' + LineEnding +
'Library" must include any data and utility programs needed for' + LineEnding +
'reproducing the executable from it.  However, as a special exception,' + LineEnding +
'the materials to be distributed need not include anything that is' + LineEnding +
'normally distributed (in either source or binary form) with the major' + LineEnding +
'components (compiler, kernel, and so on) of the operating system on' + LineEnding +
'which the executable runs, unless that component itself accompanies' + LineEnding +
'the executable.' + LineEnding +
'' + LineEnding +
'  It may happen that this requirement contradicts the license' + LineEnding +
'restrictions of other proprietary libraries that do not normally' + LineEnding +
'accompany the operating system.  Such a contradiction means you cannot' + LineEnding +
'use both them and the Library together in an executable that you' + LineEnding +
'distribute.' + LineEnding +
'' + LineEnding +
'  7. You may place library facilities that are a work based on the' + LineEnding +
'Library side-by-side in a single library together with other library' + LineEnding +
'facilities not covered by this License, and distribute such a combined' + LineEnding +
'library, provided that the separate distribution of the work based on' + LineEnding +
'the Library and of the other library facilities is otherwise' + LineEnding +
'permitted, and provided that you do these two things:' + LineEnding +
'' + LineEnding +
'    a) Accompany the combined library with a copy of the same work' + LineEnding +
'    based on the Library, uncombined with any other library' + LineEnding +
'    facilities.  This must be distributed under the terms of the' + LineEnding +
'    Sections above.' + LineEnding +
'' + LineEnding +
'    b) Give prominent notice with the combined library of the fact' + LineEnding +
'    that part of it is a work based on the Library, and explaining' + LineEnding +
'    where to find the accompanying uncombined form of the same work.' + LineEnding +
'' + LineEnding +
'  8. You may not copy, modify, sublicense, link with, or distribute' + LineEnding +
'the Library except as expressly provided under this License.  Any' + LineEnding +
'attempt otherwise to copy, modify, sublicense, link with, or' + LineEnding +
'distribute the Library is void, and will automatically terminate your' + LineEnding +
'rights under this License.  However, parties who have received copies,' + LineEnding +
'or rights, from you under this License will not have their licenses' + LineEnding +
'terminated so long as such parties remain in full compliance.' + LineEnding +
'' + LineEnding +
'  9. You are not required to accept this License, since you have not' + LineEnding +
'signed it.  However, nothing else grants you permission to modify or' + LineEnding +
'distribute the Library or its derivative works.  These actions are' + LineEnding +
'prohibited by law if you do not accept this License.  Therefore, by' + LineEnding +
'modifying or distributing the Library (or any work based on the' + LineEnding +
'Library), you indicate your acceptance of this License to do so, and' + LineEnding +
'all its terms and conditions for copying, distributing or modifying' + LineEnding +
'the Library or works based on it.' + LineEnding +
'' + LineEnding +
'  10. Each time you redistribute the Library (or any work based on the' + LineEnding +
'Library), the recipient automatically receives a license from the' + LineEnding +
'original licensor to copy, distribute, link with or modify the Library' + LineEnding +
'subject to these terms and conditions.  You may not impose any further' + LineEnding +
'restrictions on the recipients'''' exercise of the rights granted herein.' + LineEnding +
'You are not responsible for enforcing compliance by third parties with' + LineEnding +
'this License.' + LineEnding +
'' + LineEnding +
'  11. If, as a consequence of a court judgment or allegation of patent' + LineEnding +
'infringement or for any other reason (not limited to patent issues),' + LineEnding +
'conditions are imposed on you (whether by court order, agreement or' + LineEnding +
'otherwise) that contradict the conditions of this License, they do not' + LineEnding +
'excuse you from the conditions of this License.  If you cannot' + LineEnding +
'distribute so as to satisfy simultaneously your obligations under this' + LineEnding +
'License and any other pertinent obligations, then as a consequence you' + LineEnding +
'may not distribute the Library at all.  For example, if a patent' + LineEnding +
'license would not permit royalty-free redistribution of the Library by' + LineEnding +
'all those who receive copies directly or indirectly through you, then' + LineEnding +
'the only way you could satisfy both it and this License would be to' + LineEnding +
'refrain entirely from distribution of the Library.' + LineEnding +
'' + LineEnding +
'If any portion of this section is held invalid or unenforceable under any' + LineEnding +
'particular circumstance, the balance of the section is intended to apply,' + LineEnding +
'and the section as a whole is intended to apply in other circumstances.' + LineEnding +
'' + LineEnding +
'It is not the purpose of this section to induce you to infringe any' + LineEnding +
'patents or other property right claims or to contest validity of any' + LineEnding +
'such claims; this section has the sole purpose of protecting the' + LineEnding +
'integrity of the free software distribution system which is' + LineEnding +
'implemented by public license practices.  Many people have made' + LineEnding +
'generous contributions to the wide range of software distributed' + LineEnding +
'through that system in reliance on consistent application of that' + LineEnding +
'system; it is up to the author/donor to decide if he or she is willing' + LineEnding +
'to distribute software through any other system and a licensee cannot' + LineEnding +
'impose that choice.' + LineEnding +
'' + LineEnding +
'This section is intended to make thoroughly clear what is believed to' + LineEnding +
'be a consequence of the rest of this License.' + LineEnding +
'' + LineEnding +
'  12. If the distribution and/or use of the Library is restricted in' + LineEnding +
'certain countries either by patents or by copyrighted interfaces, the' + LineEnding +
'original copyright holder who places the Library under this License may add' + LineEnding +
'an explicit geographical distribution limitation excluding those countries,' + LineEnding +
'so that distribution is permitted only in or among countries not thus' + LineEnding +
'excluded.  In such case, this License incorporates the limitation as if' + LineEnding +
'written in the body of this License.' + LineEnding +
'' + LineEnding +
'  13. The Free Software Foundation may publish revised and/or new' + LineEnding +
'versions of the Lesser General Public License from time to time.' + LineEnding +
'Such new versions will be similar in spirit to the present version,' + LineEnding +
'but may differ in detail to address new problems or concerns.' + LineEnding +
'' + LineEnding +
'Each version is given a distinguishing version number.  If the Library' + LineEnding +
'specifies a version number of this License which applies to it and' + LineEnding +
'"any later version", you have the option of following the terms and' + LineEnding +
'conditions either of that version or of any later version published by' + LineEnding +
'the Free Software Foundation.  If the Library does not specify a' + LineEnding +
'license version number, you may choose any version ever published by' + LineEnding +
'the Free Software Foundation.' + LineEnding +
'' + LineEnding +
'  14. If you wish to incorporate parts of the Library into other free' + LineEnding +
'programs whose distribution conditions are incompatible with these,' + LineEnding +
'write to the author to ask for permission.  For software which is' + LineEnding +
'copyrighted by the Free Software Foundation, write to the Free' + LineEnding +
'Software Foundation; we sometimes make exceptions for this.  Our' + LineEnding +
'decision will be guided by the two goals of preserving the free status' + LineEnding +
'of all derivatives of our free software and of promoting the sharing' + LineEnding +
'and reuse of software generally.' + LineEnding +
'' + LineEnding +
'			    NO WARRANTY' + LineEnding +
'' + LineEnding +
'  15. BECAUSE THE LIBRARY IS LICENSED FREE OF CHARGE, THERE IS NO' + LineEnding +
'WARRANTY FOR THE LIBRARY, TO THE EXTENT PERMITTED BY APPLICABLE LAW.' + LineEnding +
'EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR' + LineEnding +
'OTHER PARTIES PROVIDE THE LIBRARY "AS IS" WITHOUT WARRANTY OF ANY' + LineEnding +
'KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE' + LineEnding +
'IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR' + LineEnding +
'PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE' + LineEnding +
'LIBRARY IS WITH YOU.  SHOULD THE LIBRARY PROVE DEFECTIVE, YOU ASSUME' + LineEnding +
'THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.' + LineEnding +
'' + LineEnding +
'  16. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN' + LineEnding +
'WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY' + LineEnding +
'AND/OR REDISTRIBUTE THE LIBRARY AS PERMITTED ABOVE, BE LIABLE TO YOU' + LineEnding +
'FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR' + LineEnding +
'CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE' + LineEnding +
'LIBRARY (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING' + LineEnding +
'RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A' + LineEnding +
'FAILURE OF THE LIBRARY TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF' + LineEnding +
'SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH' + LineEnding +
'DAMAGES.' + LineEnding +
'' + LineEnding +
'		     END OF TERMS AND CONDITIONS' + LineEnding +
'' + LineEnding +
'           How to Apply These Terms to Your New Libraries' + LineEnding +
'' + LineEnding +
'  If you develop a new library, and you want it to be of the greatest' + LineEnding +
'possible use to the public, we recommend making it free software that' + LineEnding +
'everyone can redistribute and change.  You can do so by permitting' + LineEnding +
'redistribution under these terms (or, alternatively, under the terms of the' + LineEnding +
'ordinary General Public License).' + LineEnding +
'' + LineEnding +
'  To apply these terms, attach the following notices to the library.  It is' + LineEnding +
'safest to attach them to the start of each source file to most effectively' + LineEnding +
'convey the exclusion of warranty; and each file should have at least the' + LineEnding +
'"copyright" line and a pointer to where the full notice is found.' + LineEnding +
'' + LineEnding +
'    <one line to give the library''''s name and a brief idea of what it does.>' + LineEnding +
'    Copyright (C) <year>  <name of author>' + LineEnding +
'' + LineEnding +
'    This library is free software; you can redistribute it and/or' + LineEnding +
'    modify it under the terms of the GNU Lesser General Public' + LineEnding +
'    License as published by the Free Software Foundation; either' + LineEnding +
'    version 2.1 of the License, or (at your option) any later version.' + LineEnding +
'' + LineEnding +
'    This library is distributed in the hope that it will be useful,' + LineEnding +
'    but WITHOUT ANY WARRANTY; without even the implied warranty of' + LineEnding +
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU' + LineEnding +
'    Lesser General Public License for more details.' + LineEnding +
'' + LineEnding +
'    You should have received a copy of the GNU Lesser General Public' + LineEnding +
'    License along with this library; if not, write to the Free Software' + LineEnding +
'    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA' + LineEnding +
'' + LineEnding +
'Also add information on how to contact you by electronic and paper mail.' + LineEnding +
'' + LineEnding +
'You should also get your employer (if you work as a programmer) or your' + LineEnding +
'school, if any, to sign a "copyright disclaimer" for the library, if' + LineEnding +
'necessary.  Here is a sample; alter the names:' + LineEnding +
'' + LineEnding +
'  Yoyodyne, Inc., hereby disclaims all copyright interest in the' + LineEnding +
'  library `Frob'''' (a library for tweaking knobs) written by James Random Hacker.' + LineEnding +
'' + LineEnding +
'  <signature of Ty Coon>, 1 April 1990' + LineEnding +
'  Ty Coon, President of Vice' + LineEnding +
'' + LineEnding +
'That''''s all there is to it!';

  GPL_Text =
  '                    GNU GENERAL PUBLIC LICENSE' + LineEnding +
  '                       Version 2, June 1991' + LineEnding +
  '' + LineEnding +
  ' Copyright (C) 1989, 1991 Free Software Foundation, Inc.' + LineEnding +
  '                          675 Mass Ave, Cambridge, MA 02139, USA' + LineEnding +
  ' Everyone is permitted to copy and distribute verbatim copies' + LineEnding +
  ' of this license document, but changing it is not allowed.' + LineEnding +
  '' + LineEnding +
  '                            Preamble' + LineEnding +
  '' + LineEnding +
  '  The licenses for most software are designed to take away your' + LineEnding +
  'freedom to share and change it.  By contrast, the GNU General Public' + LineEnding +
  'License is intended to guarantee your freedom to share and change free' + LineEnding +
  'software--to make sure the software is free for all its users.  This' + LineEnding +
  'General Public License applies to most of the Free Software' + LineEnding +
  'Foundation''''s software and to any other program whose authors commit to' + LineEnding +
  'using it.  (Some other Free Software Foundation software is covered by' + LineEnding +
  'the GNU Library General Public License instead.)  You can apply it to' + LineEnding +
  'your programs, too.' + LineEnding +
  '' + LineEnding +
  '  When we speak of free software, we are referring to freedom, not' + LineEnding +
  'price.  Our General Public Licenses are designed to make sure that you' + LineEnding +
  'have the freedom to distribute copies of free software (and charge for' + LineEnding +
  'this service if you wish), that you receive source code or can get it' + LineEnding +
  'if you want it, that you can change the software or use pieces of it' + LineEnding +
  'in new free programs; and that you know you can do these things.' + LineEnding +
  '' + LineEnding +
  '  To protect your rights, we need to make restrictions that forbid' + LineEnding +
  'anyone to deny you these rights or to ask you to surrender the rights.' + LineEnding +
  'These restrictions translate to certain responsibilities for you if you' + LineEnding +
  'distribute copies of the software, or if you modify it.' + LineEnding +
  '' + LineEnding +
  '  For example, if you distribute copies of such a program, whether' + LineEnding +
  'gratis or for a fee, you must give the recipients all the rights that' + LineEnding +
  'you have.  You must make sure that they, too, receive or can get the' + LineEnding +
  'source code.  And you must show them these terms so they know their' + LineEnding +
  'rights.' + LineEnding +
  '' + LineEnding +
  '  We protect your rights with two steps: (1) copyright the software, and' + LineEnding +
  '(2) offer you this license which gives you legal permission to copy,' + LineEnding +
  'distribute and/or modify the software.' + LineEnding +
  '' + LineEnding +
  '  Also, for each author''''s protection and ours, we want to make certain' + LineEnding +
  'that everyone understands that there is no warranty for this free' + LineEnding +
  'software.  If the software is modified by someone else and passed on, we' + LineEnding +
  'want its recipients to know that what they have is not the original, so' + LineEnding +
  'that any problems introduced by others will not reflect on the original' + LineEnding +
  'authors'''' reputations.' + LineEnding +
  '' + LineEnding +
  '  Finally, any free program is threatened constantly by software' + LineEnding +
  'patents.  We wish to avoid the danger that redistributors of a free' + LineEnding +
  'program will individually obtain patent licenses, in effect making the' + LineEnding +
  'program proprietary.  To prevent this, we have made it clear that any' + LineEnding +
  'patent must be licensed for everyone''''s free use or not licensed at all.' + LineEnding +
  '' + LineEnding +
  '  The precise terms and conditions for copying, distribution and' + LineEnding +
  'modification follow.' + LineEnding +
  '' + LineEnding +
  '                    GNU GENERAL PUBLIC LICENSE' + LineEnding +
  '   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION' + LineEnding +
  '' + LineEnding +
  '  0. This License applies to any program or other work which contains' + LineEnding +
  'a notice placed by the copyright holder saying it may be distributed' + LineEnding +
  'under the terms of this General Public License.  The "Program", below,' + LineEnding +
  'refers to any such program or work, and a "work based on the Program"' + LineEnding +
  'means either the Program or any derivative work under copyright law:' + LineEnding +
  'that is to say, a work containing the Program or a portion of it,' + LineEnding +
  'either verbatim or with modifications and/or translated into another' + LineEnding +
  'language.  (Hereinafter, translation is included without limitation in' + LineEnding +
  'the term "modification".)  Each licensee is addressed as "you".' + LineEnding +
  '' + LineEnding +
  'Activities other than copying, distribution and modification are not' + LineEnding +
  'covered by this License; they are outside its scope.  The act of' + LineEnding +
  'running the Program is not restricted, and the output from the Program' + LineEnding +
  'is covered only if its contents constitute a work based on the' + LineEnding +
  'Program (independent of having been made by running the Program).' + LineEnding +
  'Whether that is true depends on what the Program does.' + LineEnding +
  '' + LineEnding +
  '  1. You may copy and distribute verbatim copies of the Program''''s' + LineEnding +
  'source code as you receive it, in any medium, provided that you' + LineEnding +
  'conspicuously and appropriately publish on each copy an appropriate' + LineEnding +
  'copyright notice and disclaimer of warranty; keep intact all the' + LineEnding +
  'notices that refer to this License and to the absence of any warranty;' + LineEnding +
  'and give any other recipients of the Program a copy of this License' + LineEnding +
  'along with the Program.' + LineEnding +
  '' + LineEnding +
  'You may charge a fee for the physical act of transferring a copy, and' + LineEnding +
  'you may at your option offer warranty protection in exchange for a fee.' + LineEnding +
  '' + LineEnding +
  '  2. You may modify your copy or copies of the Program or any portion' + LineEnding +
  'of it, thus forming a work based on the Program, and copy and' + LineEnding +
  'distribute such modifications or work under the terms of Section 1' + LineEnding +
  'above, provided that you also meet all of these conditions:' + LineEnding +
  '' + LineEnding +
  '    a) You must cause the modified files to carry prominent notices' + LineEnding +
  '    stating that you changed the files and the date of any change.' + LineEnding +
  '' + LineEnding +
  '    b) You must cause any work that you distribute or publish, that in' + LineEnding +
  '    whole or in part contains or is derived from the Program or any' + LineEnding +
  '    part thereof, to be licensed as a whole at no charge to all third' + LineEnding +
  '    parties under the terms of this License.' + LineEnding +
  '' + LineEnding +
  '    c) If the modified program normally reads commands interactively' + LineEnding +
  '    when run, you must cause it, when started running for such' + LineEnding +
  '    interactive use in the most ordinary way, to print or display an' + LineEnding +
  '    announcement including an appropriate copyright notice and a' + LineEnding +
  '    notice that there is no warranty (or else, saying that you provide' + LineEnding +
  '    a warranty) and that users may redistribute the program under' + LineEnding +
  '    these conditions, and telling the user how to view a copy of this' + LineEnding +
  '    License.  (Exception: if the Program itself is interactive but' + LineEnding +
  '    does not normally print such an announcement, your work based on' + LineEnding +
  '    the Program is not required to print an announcement.)' + LineEnding +
  '' + LineEnding +
  'These requirements apply to the modified work as a whole.  If' + LineEnding +
  'identifiable sections of that work are not derived from the Program,' + LineEnding +
  'and can be reasonably considered independent and separate works in' + LineEnding +
  'themselves, then this License, and its terms, do not apply to those' + LineEnding +
  'sections when you distribute them as separate works.  But when you' + LineEnding +
  'distribute the same sections as part of a whole which is a work based' + LineEnding +
  'on the Program, the distribution of the whole must be on the terms of' + LineEnding +
  'this License, whose permissions for other licensees extend to the' + LineEnding +
  'entire whole, and thus to each and every part regardless of who wrote it.' + LineEnding +
  '' + LineEnding +
  'Thus, it is not the intent of this section to claim rights or contest' + LineEnding +
  'your rights to work written entirely by you; rather, the intent is to' + LineEnding +
  'exercise the right to control the distribution of derivative or' + LineEnding +
  'collective works based on the Program.' + LineEnding +
  '' + LineEnding +
  'In addition, mere aggregation of another work not based on the Program' + LineEnding +
  'with the Program (or with a work based on the Program) on a volume of' + LineEnding +
  'a storage or distribution medium does not bring the other work under' + LineEnding +
  'the scope of this License.' + LineEnding +
  '' + LineEnding +
  '  3. You may copy and distribute the Program (or a work based on it,' + LineEnding +
  'under Section 2) in object code or executable form under the terms of' + LineEnding +
  'Sections 1 and 2 above provided that you also do one of the following:' + LineEnding +
  '' + LineEnding +
  '    a) Accompany it with the complete corresponding machine-readable' + LineEnding +
  '    source code, which must be distributed under the terms of Sections' + LineEnding +
  '    1 and 2 above on a medium customarily used for software interchange; or,' + LineEnding +
  '' + LineEnding +
  '    b) Accompany it with a written offer, valid for at least three' + LineEnding +
  '    years, to give any third party, for a charge no more than your' + LineEnding +
  '    cost of physically performing source distribution, a complete' + LineEnding +
  '    machine-readable copy of the corresponding source code, to be' + LineEnding +
  '    distributed under the terms of Sections 1 and 2 above on a medium' + LineEnding +
  '    customarily used for software interchange; or,' + LineEnding +
  '' + LineEnding +
  '    c) Accompany it with the information you received as to the offer' + LineEnding +
  '    to distribute corresponding source code.  (This alternative is' + LineEnding +
  '    allowed only for noncommercial distribution and only if you' + LineEnding +
  '    received the program in object code or executable form with such' + LineEnding +
  '    an offer, in accord with Subsection b above.)' + LineEnding +
  '' + LineEnding +
  'The source code for a work means the preferred form of the work for' + LineEnding +
  'making modifications to it.  For an executable work, complete source' + LineEnding +
  'code means all the source code for all modules it contains, plus any' + LineEnding +
  'associated interface definition files, plus the scripts used to' + LineEnding +
  'control compilation and installation of the executable.  However, as a' + LineEnding +
  'special exception, the source code distributed need not include' + LineEnding +
  'anything that is normally distributed (in either source or binary' + LineEnding +
  'form) with the major components (compiler, kernel, and so on) of the' + LineEnding +
  'operating system on which the executable runs, unless that component' + LineEnding +
  'itself accompanies the executable.' + LineEnding +
  '' + LineEnding +
  'If distribution of executable or object code is made by offering' + LineEnding +
  'access to copy from a designated place, then offering equivalent' + LineEnding +
  'access to copy the source code from the same place counts as' + LineEnding +
  'distribution of the source code, even though third parties are not' + LineEnding +
  'compelled to copy the source along with the object code.' + LineEnding +
  '' + LineEnding +
  '  4. You may not copy, modify, sublicense, or distribute the Program' + LineEnding +
  'except as expressly provided under this License.  Any attempt' + LineEnding +
  'otherwise to copy, modify, sublicense or distribute the Program is' + LineEnding +
  'void, and will automatically terminate your rights under this License.' + LineEnding +
  'However, parties who have received copies, or rights, from you under' + LineEnding +
  'this License will not have their licenses terminated so long as such' + LineEnding +
  'parties remain in full compliance.' + LineEnding +
  '' + LineEnding +
  '  5. You are not required to accept this License, since you have not' + LineEnding +
  'signed it.  However, nothing else grants you permission to modify or' + LineEnding +
  'distribute the Program or its derivative works.  These actions are' + LineEnding +
  'prohibited by law if you do not accept this License.  Therefore, by' + LineEnding +
  'modifying or distributing the Program (or any work based on the' + LineEnding +
  'Program), you indicate your acceptance of this License to do so, and' + LineEnding +
  'all its terms and conditions for copying, distributing or modifying' + LineEnding +
  'the Program or works based on it.' + LineEnding +
  '' + LineEnding +
  '  6. Each time you redistribute the Program (or any work based on the' + LineEnding +
  'Program), the recipient automatically receives a license from the' + LineEnding +
  'original licensor to copy, distribute or modify the Program subject to' + LineEnding +
  'these terms and conditions.  You may not impose any further' + LineEnding +
  'restrictions on the recipients'''' exercise of the rights granted herein.' + LineEnding +
  'You are not responsible for enforcing compliance by third parties to' + LineEnding +
  'this License.' + LineEnding +
  '' + LineEnding +
  '  7. If, as a consequence of a court judgment or allegation of patent' + LineEnding +
  'infringement or for any other reason (not limited to patent issues),' + LineEnding +
  'conditions are imposed on you (whether by court order, agreement or' + LineEnding +
  'otherwise) that contradict the conditions of this License, they do not' + LineEnding +
  'excuse you from the conditions of this License.  If you cannot' + LineEnding +
  'distribute so as to satisfy simultaneously your obligations under this' + LineEnding +
  'License and any other pertinent obligations, then as a consequence you' + LineEnding +
  'may not distribute the Program at all.  For example, if a patent' + LineEnding +
  'license would not permit royalty-free redistribution of the Program by' + LineEnding +
  'all those who receive copies directly or indirectly through you, then' + LineEnding +
  'the only way you could satisfy both it and this License would be to' + LineEnding +
  'refrain entirely from distribution of the Program.' + LineEnding +
  '' + LineEnding +
  'If any portion of this section is held invalid or unenforceable under' + LineEnding +
  'any particular circumstance, the balance of the section is intended to' + LineEnding +
  'apply and the section as a whole is intended to apply in other' + LineEnding +
  'circumstances.' + LineEnding +
  '' + LineEnding +
  'It is not the purpose of this section to induce you to infringe any' + LineEnding +
  'patents or other property right claims or to contest validity of any' + LineEnding +
  'such claims; this section has the sole purpose of protecting the' + LineEnding +
  'integrity of the free software distribution system, which is' + LineEnding +
  'implemented by public license practices.  Many people have made' + LineEnding +
  'generous contributions to the wide range of software distributed' + LineEnding +
  'through that system in reliance on consistent application of that' + LineEnding +
  'system; it is up to the author/donor to decide if he or she is willing' + LineEnding +
  'to distribute software through any other system and a licensee cannot' + LineEnding +
  'impose that choice.' + LineEnding +
  '' + LineEnding +
  'This section is intended to make thoroughly clear what is believed to' + LineEnding +
  'be a consequence of the rest of this License.' + LineEnding +
  '' + LineEnding +
  '  8. If the distribution and/or use of the Program is restricted in' + LineEnding +
  'certain countries either by patents or by copyrighted interfaces, the' + LineEnding +
  'original copyright holder who places the Program under this License' + LineEnding +
  'may add an explicit geographical distribution limitation excluding' + LineEnding +
  'those countries, so that distribution is permitted only in or among' + LineEnding +
  'countries not thus excluded.  In such case, this License incorporates' + LineEnding +
  'the limitation as if written in the body of this License.' + LineEnding +
  '' + LineEnding +
  '  9. The Free Software Foundation may publish revised and/or new versions' + LineEnding +
  'of the General Public License from time to time.  Such new versions will' + LineEnding +
  'be similar in spirit to the present version, but may differ in detail to' + LineEnding +
  'address new problems or concerns.' + LineEnding +
  '' + LineEnding +
  'Each version is given a distinguishing version number.  If the Program' + LineEnding +
  'specifies a version number of this License which applies to it and "any' + LineEnding +
  'later version", you have the option of following the terms and conditions' + LineEnding +
  'either of that version or of any later version published by the Free' + LineEnding +
  'Software Foundation.  If the Program does not specify a version number of' + LineEnding +
  'this License, you may choose any version ever published by the Free Software' + LineEnding +
  'Foundation.' + LineEnding +
  '' + LineEnding +
  '  10. If you wish to incorporate parts of the Program into other free' + LineEnding +
  'programs whose distribution conditions are different, write to the author' + LineEnding +
  'to ask for permission.  For software which is copyrighted by the Free' + LineEnding +
  'Software Foundation, write to the Free Software Foundation; we sometimes' + LineEnding +
  'make exceptions for this.  Our decision will be guided by the two goals' + LineEnding +
  'of preserving the free status of all derivatives of our free software and' + LineEnding +
  'of promoting the sharing and reuse of software generally.' + LineEnding +
  '' + LineEnding +
  '                            NO WARRANTY' + LineEnding +
  '' + LineEnding +
  '  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY' + LineEnding +
  'FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN' + LineEnding +
  'OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES' + LineEnding +
  'PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED' + LineEnding +
  'OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF' + LineEnding +
  'MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS' + LineEnding +
  'TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE' + LineEnding +
  'PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,' + LineEnding +
  'REPAIR OR CORRECTION.' + LineEnding +
  '' + LineEnding +
  '  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING' + LineEnding +
  'WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR' + LineEnding +
  'REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,' + LineEnding +
  'INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING' + LineEnding +
  'OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED' + LineEnding +
  'TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY' + LineEnding +
  'YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER' + LineEnding +
  'PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE' + LineEnding +
  'POSSIBILITY OF SUCH DAMAGES.' + LineEnding +
  '' + LineEnding +
  '                     END OF TERMS AND CONDITIONS' + LineEnding +
  '' + LineEnding +
  '        Appendix: How to Apply These Terms to Your New Programs' + LineEnding +
  '' + LineEnding +
  '  If you develop a new program, and you want it to be of the greatest' + LineEnding +
  'possible use to the public, the best way to achieve this is to make it' + LineEnding +
  'free software which everyone can redistribute and change under these terms.' + LineEnding +
  '' + LineEnding +
  '  To do so, attach the following notices to the program.  It is safest' + LineEnding +
  'to attach them to the start of each source file to most effectively' + LineEnding +
  'convey the exclusion of warranty; and each file should have at least' + LineEnding +
  'the "copyright" line and a pointer to where the full notice is found.' + LineEnding +
  '' + LineEnding +
  '    <one line to give the program''''s name and a brief idea of what it does.>' + LineEnding +
  '    Copyright (C) 19yy  <name of author>' + LineEnding +
  '' + LineEnding +
  '    This program is free software; you can redistribute it and/or modify' + LineEnding +
  '    it under the terms of the GNU General Public License as published by' + LineEnding +
  '    the Free Software Foundation; either version 2 of the License, or' + LineEnding +
  '    (at your option) any later version.' + LineEnding +
  '' + LineEnding +
  '    This program is distributed in the hope that it will be useful,' + LineEnding +
  '    but WITHOUT ANY WARRANTY; without even the implied warranty of' + LineEnding +
  '    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the' + LineEnding +
  '    GNU General Public License for more details.' + LineEnding +
  '' + LineEnding +
  '    You should have received a copy of the GNU General Public License' + LineEnding +
  '    along with this program; if not, write to the Free Software' + LineEnding +
  '    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.' + LineEnding +
  '' + LineEnding +
  'Also add information on how to contact you by electronic and paper mail.' + LineEnding +
  '' + LineEnding +
  'If the program is interactive, make it output a short notice like this' + LineEnding +
  'when it starts in an interactive mode:' + LineEnding +
  '' + LineEnding +
  '    Gnomovision version 69, Copyright (C) 19yy name of author' + LineEnding +
  '    Gnomovision comes with ABSOLUTELY NO WARRANTY; for details type `show w''''.' + LineEnding +
  '    This is free software, and you are welcome to redistribute it' + LineEnding +
  '    under certain conditions; type `show c'''' for details.' + LineEnding +
  '' + LineEnding +
  'The hypothetical commands `show w'''' and `show c'''' should show the appropriate' + LineEnding +
  'parts of the General Public License.  Of course, the commands you use may' + LineEnding +
  'be called something other than `show w'''' and `show c''''; they could even be' + LineEnding +
  'mouse-clicks or menu items--whatever suits your program.' + LineEnding +
  '' + LineEnding +
  'You should also get your employer (if you work as a programmer) or your' + LineEnding +
  'school, if any, to sign a "copyright disclaimer" for the program, if' + LineEnding +
  'necessary.  Here is a sample; alter the names:' + LineEnding +
  '' + LineEnding +
  '  Yoyodyne, Inc., hereby disclaims all copyright interest in the program' + LineEnding +
  '  `Gnomovision'''' (which makes passes at compilers) written by James Hacker.' + LineEnding +
  '' + LineEnding +
  '  <signature of Ty Coon>, 1 April 1989' + LineEnding +
  '  Ty Coon, President of Vice' + LineEnding +
  '' + LineEnding +
  'This General Public License does not permit incorporating your program into' + LineEnding +
  'proprietary programs.  If your program is a subroutine library, you may' + LineEnding +
  'consider it more useful to permit linking proprietary applications with the' + LineEnding +
  'library.  If this is what you want to do, use the GNU Library General' + LineEnding +
  'Public License instead of this License.';

  LGPL_URL = 'http://www.gnu.org/licenses/old-licenses/library.html';

