<?xml version="1.0"?>
<definitions name="wst_test" 
   xmlns="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:tns="library1" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
   targetNamespace="urn:wst-test">

  <types>

      <xsd:schema xmlns:n="urn:wst-test" 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:wst-test">
  
          <xsd:complexType name="TSampleType1">
      	    <xsd:choice>
      		    <xsd:element name="intField" type="xsd:int" />
              <xsd:element name="strField" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      	    </xsd:choice>
          </xsd:complexType>
    
      </xsd:schema>  
  
  </types>
  

</definitions>
