<?xml version="1.0"?>
<definitions name="wst_test" 
   xmlns="http://schemas.xmlsoap.org/wsdl/" 
   xmlns:tns="library1" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
   xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
   targetNamespace="urn:wst-test">

  <types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:wst-test">
    
         <xsd:complexType name="TArrayIntFieldType">
            <xsd:complexContent>
               <xsd:restriction base="soapenc:Array">
                  <xsd:sequence />
                  <xsd:attribute ref="soapenc:arrayType" n1:arrayType="xsd:int[]" xmlns:n1="http://schemas.xmlsoap.org/wsdl/" />
               </xsd:restriction>
            </xsd:complexContent>
         </xsd:complexType>      
    
    </xsd:schema>
  </types>
  

</definitions>
