<?xml version="1.0"?>
<definitions name="library1" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="library1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="library1">
  <types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="library1" targetNamespace="library1"/>
  </types>
  
  <message name="sampleProc">
    <part name="AInParam" type="xsd:string"/>
    <part name="AInOutParam" type="xsd:int"/>
  </message>
  <message name="sampleProcResponse">
    <part name="AInOutParam" type="xsd:int"/>
  </message>
  
  <message name="sampleProc2">
    <part name="AInParam" type="xsd:string"/>
    <part name="AInOutParam" type="xsd:int"/>
  </message>
  <message name="sampleProc2Response">
    <part name="AInOutParam" type="xsd:byte"/>
  </message>
    
  <portType name="TestService">
    <document>
      <GUID value="{061EA53B-871D-45AE-9714-33EFF4069818}"/>
    </document>
    <operation name="sampleProc">
      <input message="tns:sampleProc"/>
      <output message="tns:sampleProcResponse"/>
    </operation>
    <operation name="sampleProc2">
      <input message="tns:sampleProc2"/>
      <output message="tns:sampleProc2Response"/>
    </operation>    
  </portType>
  <binding name="TestServiceBinding" type="tns:TestService">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="sampleProc">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="library1"/>
      </input>
      <output>
        <soap:body use="literal" namespace="library1"/>
      </output>
    </operation>
    <operation name="sampleProc2">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="library1"/>
      </input>
      <output>
        <soap:body use="literal" namespace="library1"/>
      </output>
    </operation>    
  </binding>
  <service name="TestService">
    <port name="TestServicePort" binding="tns:TestServiceBinding">
      <soap:address location=""/>
    </port>
  </service>
</definitions>
