<?xml version="1.0"?>
<definitions name="runtime_generator" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:sample-namespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:sample-namespace">
  <types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wst="urn:wst_base" targetNamespace="urn:sample-namespace">
      <xsd:complexType name="TTestSmallRecord" wst:wst_record="true">
        <xsd:sequence>
          <xsd:element name="fieldSmallint" type="xsd:short" maxOccurs="1" minOccurs="0"/>
          <xsd:element name="fieldString" type="xsd:string" maxOccurs="1" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute use="optional" name="fieldWord" type="xsd:unsignedShort"/>
      </xsd:complexType>
    </xsd:schema>
  </types>
</definitions>
